README.md, examples/cloud_run_vpc_connector/README.md, examples/cloud_run_vpc_connector/outputs.tf, main.tf, variables.tf
This includes minor changes to the descriptions, required variables and README corrections, identified from Terraform Registry.
=> fix: Updates to README and descriptions

.github/release-please.yml, Makefile, build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml, examples/cloud_run_vpc_connector/network.tf, examples/cloud_run_vpc_connector/versions.tf, kitchen.yml, test/integration/simple_cloud_run/inspec.yml, versions.tf
fixes https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/issues/24
=> feat: update TPG version constraints to allow 4.0

README.md, variables.tf
Set default variable values to fix #30
=> Set default container limits and concurrency value

modules/secure-cloud-run-net/README.md, modules/secure-cloud-run-net/firewall.tf, modules/secure-cloud-run-net/iam.tf, modules/secure-cloud-run-net/network.tf, modules/secure-cloud-run-net/outputs.tf, modules/secure-cloud-run-net/variables.tf, modules/secure-cloud-run-net/versions.tf
Hello you all,
This pull request adds a new sub-module to create network to be used by Cloud Run.
Could you, please, take a look on it?
Thanks!
=> Add 'secure-cloud-run-net' sub-module

modules/secure-cloud-run-net/README.md, modules/secure-cloud-run-net/iam.tf, modules/secure-cloud-run-net/variables.tf
Hello you all,
This pull request change the default value for variable _connector_on_host_project_ to **false** and also change the role _roles/compute.networkAdmin_ to **roles/compute.networkUser** for the VPC Access Identity Service Account.
Could you, please, take a look on it?
Thanks!
=> secure-cloud-run-net fixes.

modules/secure-cloud-run-core/README.md, modules/secure-cloud-run-core/loadbalancer.tf, modules/secure-cloud-run-core/variables.tf, modules/secure-cloud-run/README.md, modules/secure-cloud-run/main.tf, modules/secure-cloud-run/outputs.tf, modules/secure-cloud-run/variables.tf, modules/secure-cloud-run/versions.tf
Hello Folks, 
This pull request adds a new sub-module to create the main sub-module to be used by Cloud Run.
Can you please take a look on it?
Thank you!
=> Adds secure-cloud-run main submodule

modules/secure-cloud-run-security/README.md, modules/secure-cloud-run-security/org_policies.tf, modules/secure-cloud-run-security/variables.tf
Hey Folks,
This pull request allows the customer to choose in which level (project, folder or organization) the secure-cloud-run org-policies will be applied.
Can you please take a look on it?
Thank you!
=> Adding option to setup where org-policies will be applied

examples/secure_cloud_run_standalone/README.md, modules/secure-cloud-run-harness/README.md
This PR adds instructions, requirements and the resources that are going to be created by the terraform code.
=> Improves Harness and Standalone READMEs

modules/secure-cloud-run-core/README.md, modules/secure-cloud-run-core/variables.tf
This PR adds instructions and requirements for secure-cloud-run module.
=> Adds instructions in cloud run core sub-module

modules/secure-cloud-run-net/README.md, modules/secure-cloud-run-net/variables.tf
This PR adds requirements and details of what is created by `secure-cloud-run-net` sub-module
=> Adds requirements on secure-cloud-run-net module

modules/secure-cloud-run-security/README.md
This PR fixes requirements order in the readme
=> fixes requirements section place

build/int.cloudbuild.yaml, examples/secure_cloud_run_standalone/README.md, examples/secure_cloud_run_standalone/terraform.example.tfvars, examples/secure_cloud_run_standalone/variables.tf
This PR adds some improvements about access_context_manager and more detailed description.
=> Adds improvements to access_context_manager

Makefile, build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml, examples/cloud_run_vpc_connector/network.tf, examples/secure_cloud_run/README.md, examples/secure_cloud_run/variables.tf, examples/secure_cloud_run_standalone/README.md, examples/secure_cloud_run_standalone/main.tf, examples/secure_cloud_run_standalone/variables.tf, main.tf, modules/secure-cloud-run-core/variables.tf, modules/secure-cloud-run-core/versions.tf, modules/secure-cloud-run-harness/versions.tf, modules/secure-cloud-run-net/firewall.tf
New updates from renovate bots requires Go 1.18 which is not available in Developer Tools 1.7.
Also closes duplicate PR #105
=> fix: dev tools to 1.10 for Go 1.18

modules/secure-serverless-harness/README.md, modules/secure-serverless-harness/main.tf, modules/secure-serverless-harness/network.tf, modules/secure-serverless-harness/outputs.tf, modules/secure-serverless-harness/private_service_connect.tf, modules/secure-serverless-harness/service_perimeter.tf, modules/secure-serverless-harness/variables.tf
This PR adds variable to customize the time_sleep to wait VPC-SC propagation. Default is 3 minutes.
=> feat: Creates variable to customize time_sleep due VPC-SC  propagation time

modules/secure-serverless-harness/service_perimeter.tf
This PR  replaces the random_id used in the composition of the names of the Access Level and Perimeter created in the `secure-serverless-harness` so that instead of a space with `[0-9a-f](4)` we will have `[0-9a-z](4)` which will decrease the chance of a collision of names when running tests
```
Error: Error creating AccessPolicy: googleapi: Error 409: Policy already exists with parent organizations/00000000000000
```
=> fix!: replace random_id with random_string to increase number of possible access levels

Makefile, modules/v2/main.tf, modules/v2/metadata.yaml
This PR makes below changes,
1. Fixes typo in v2/main.tf for creating GCS volume fixes https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/issues/230
2. Adds new connection metadata coming from GCS
3. Adds new connection metadata coming from Mysql (similar to existing postgresql module)
=> fix: Add connection metadata for incoming connection from GCS and fix typo in v2/main.tf

build/int.cloudbuild.yaml
Serialize test execution to avoid provider version conflict. One such GCB issue: https://pantheon.corp.google.com/cloud-build/builds/de87846b-bf0e-48ac-b7bd-f092f2d578f1;step=16?e=13835675&mods=logs_tg_test&project=cloud-foundation-cicd
=> chore: Update int.cloudbuild.yaml

modules/v2/main.tf, modules/v2/metadata.display.yaml, modules/v2/metadata.yaml
This PR makes below changes,
* Add connection metadata for connecting with vertex-ai dummy module
* updates metadata.display.yaml
* adds alternate default for containers
=> fix: add connection metadata and display metadata

modules/job-exec/versions.tf, modules/secure-cloud-run-core/versions.tf, modules/secure-cloud-run-security/versions.tf, modules/secure-cloud-run/versions.tf, modules/secure-serverless-harness/versions.tf, modules/secure-serverless-net/versions.tf, modules/service-project-factory/versions.tf, modules/v2/versions.tf, test/fixtures/secure_cloud_run/versions.tf, test/fixtures/simple_cloud_run/versions.tf, versions.tf
add lower version constraint to Terraform Google provider (`deletion_protection` was added/required in TPG v6)
Fixes: https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/pull/257, https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/pull/275
=> fix: add lower version constraint to Terraform Google provider

build/int.cloudbuild.yaml, examples/v2_with_gmp/main.tf, modules/v2/metadata.yaml, modules/v2/outputs.tf, test/integration/v2_with_gmp/v2_with_gmp_test.go, test/setup/iam.tf
In addition to adding test for cloud-run v2 with gmp, this PR makes below changes,
* Adds IAM role for deployment service account to assign roles to the cloud-run SA
* Adds location field in apphub_service_uri
=> fix: add test for cloud-run v2 with gmp container

modules/v2/metadata.yaml
When connection to pubsub is created:
* Add `TOPIC_ID` environment variable
* Grant `roles/pubsub.publisher`, `roles/pubsub.subscriber` roles for specified project
=> chore: add pubsub connection metadata

examples/v2/main.tf, modules/v2/main.tf, modules/v2/metadata.yaml
With this change, service_accout_id would always be present even if the service_account creation is disabled as part of the cloud-run blueprint.
This PR also update to skip assigning any roles is SA is not created by the blueprint. When a user provides as SA, they are in control for assigning any roles. b/396010348
=> fix: update service_account_id output variable

modules/v2/metadata.yaml
`roles/run.invoker` is required for 
The oidc-service-account email used for
The push subscription created via an Cloud Run -> Pub/Sub ADC connection requires a service account with `roles/run.invoker`. We satisfy this requirement by granting `roles/run.invoker` to the Cloud Run service account.
=> chore: grant run.invoker role when connection to pubsub

modules/v2/main.tf
This PR addresses the bug reported in https://github.com/GoogleCloudPlatform/terraform-google-cloud-run/issues/360
=> fix: trigger google_compute_default_service_account datasource only if the service account name is not provided

modules/v2/metadata.yaml
This PR establishes the necessary connections with Memorystore's GitHub repository.
Purpose: This is an essential step in adding connection_metadata for Memorystore Redis Clusters (MRC), a crucial part of our process to onboard MRC to Application Design Center (ADC).
=> feat: Add connections for Memorystore in metadata.yaml
